#!/bin/sh

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# General
/usr/lib/polkit-kde-authentication-agent-1 &
dunst &
set_random_wallpaper
blueman-applet &
nm-applet &
mpc --port=6606 repeat on
pactl load-module module-switch-on-connect # pipewire-pulseaudio set newly connected devices as default
/home/le0/.local/bin/mouse_set_sens
synology-drive autostart &

# Xorg
setxkbmap -layout us,ru -option grp:alt_shift_toggle
kbdd &

exec qtile start
#exec i3
