set number	
set linebreak
set showbreak=+++
set textwidth=100
set showmatch
set virtualedit=insert

syntax on

set hlsearch	
set smartcase	
set ignorecase	
set incsearch	
 
filetype plugin indent on

set autoindent	
set shiftwidth=4
set smartindent	
set smarttab
set softtabstop=4	
 
set ruler	
set showcmd
 
set undolevels=1000
set backspace=indent,eol,start	
