#!/bin/bash


function get_username {
    id | awk '{ print $2 }' | awk -F '(' '{ print $2 }' | awk -F ')' '{ print $1 }'
}

cd /tmp
git clone https://aur.archlinux.org/yay.git
sudo chown -R $(get_username) yay
cd yay
makepkg -si
cd ..
rm- -rf yay
